### PR TITLE
Save/load character inventory - Fixes #813

### LINKED ISSUE #813: Load/Save doesn't work
There is an exception thrown when trying to write the xml for inventory so it doesn't write the file.

### PR DESCRIPTION
**Pull request by koosemose**
Characters now save their inventory, and load it at start.
Inventory Sprite controller only creates a game object when tile isn't null
Inventory WriteXml only writes inventory when tile isn't null

### CODE REVIEW

File: Assets/Scripts/Models/World.cs [hunk 1]
```diff
@@ -632,7 +632,7 @@ void LoadInventoryPrototypesFromFile(string inventoryXmlText)
         //furniturePrototypes["Door"].RegisterUpdateAction( FurnitureActions.Door_UpdateAction );
         //furniturePrototypes["Door"].IsEnterable = FurnitureActions.Door_IsEnterable;
 
-            //Logger.LogError("Did not find a 'Inventories' element in the prototype definition file.");
+        //Logger.LogError("Did not find a 'Inventories' element in the prototype definition file.");
```
Comment (Grenkin1988) [inline Assets/Scripts/Models/World.cs]: Remove commented code

Comment (koosemose) [inline Assets/Scripts/Models/World.cs]: I'm trying to figure out why it even says I changed that line... I guess at some point I changed the spacing... strange.

File: Assets/Scripts/Models/World.cs [hunk 2]
```diff
@@ -1063,24 +1068,42 @@ void ReadXml_Characters(XmlReader reader)
             {
                 int x = int.Parse(reader.GetAttribute("X"));
                 int y = int.Parse(reader.GetAttribute("Y"));
+                Character c;
```
Comment (Grenkin1988) [inline Assets/Scripts/Models/World.cs]: Please name this variable as character. At the end of method you already trying to remember what is "c"

File: Assets/Scripts/Models/World.cs (hunk 1 above)
Comment (Grenkin1988) [inline Assets/Scripts/Models/World.cs]: Still it's better to clean up code, even if not you made this

File: Assets/Scripts/Models/Character.cs [hunk 3]
```diff
@@ -800,6 +800,15 @@ public void WriteXml(XmlWriter writer)
         writer.WriteAttributeString("r", characterColor.r.ToString());
         writer.WriteAttributeString("b", characterColor.b.ToString());
         writer.WriteAttributeString("g", characterColor.g.ToString());
+        if (inventory != null)
+        {
+
```
Comment (Grenkin1988) [inline Assets/Scripts/Models/Character.cs]: Unnecessary new line

File: Assets/Scripts/Models/World.cs [hunk 4]
```diff
@@ -400,8 +400,8 @@ void CreateNeedPrototypes()
 
     void LoadNeedPrototypesFromFile(string needXmlText)
     {
-        
-        
+
+
```
Comment (Grenkin1988) [inline Assets/Scripts/Models/World.cs]: Unnecessary new line

File: Assets/Scripts/Models/World.cs [hunk 5]
```diff
@@ -732,7 +732,7 @@ public Tile GetFirstCenterTileWithNoInventory(int maxOffset)
                     return tile;
                 }
             }
-            
+
```
Comment (Grenkin1988) [inline Assets/Scripts/Models/World.cs]: Unnecessary new line

File: Assets/Scripts/Models/World.cs (hunk 1 above)
Comment (koosemose) [inline Assets/Scripts/Models/World.cs]: Yes but after 12 hours straight coding I really don't have the patience to fix every style error that was preexisting in code I've touched.

I hope you'll pardon me, but I am entirely too tired and mind-fried to handle your comments in a polite tone to match your own.

Comment (Grenkin1988) [inline Assets/Scripts/Models/World.cs]: Do not know who asked you to 12 hours straight coding. Purpose of coding standard is that it is no my own.
But what the hell, you could leave as is.
But that you will the next who will read it and think who the hell wrote this...

File: Assets/Scripts/Models/World.cs (hunk 5 above)
Comment (koosemose) [inline Assets/Scripts/Models/World.cs]: This is getting ridiculous.

File: Assets/Scripts/Models/World.cs [hunk 6]
```diff
@@ -1063,24 +1064,42 @@ void ReadXml_Characters(XmlReader reader)
...
                 {
                     float r = float.Parse(reader.GetAttribute("r"));
                     float b = float.Parse(reader.GetAttribute("b"));;
                     float g = float.Parse(reader.GetAttribute("g"));;
                     Color color = new Color(r, g, b, 1.0f);
-                    Character c = CreateCharacter(tiles[x, y], color);
-                    c.name = reader.GetAttribute("name");
-                    c.ReadXml(reader);
+                    character = CreateCharacter(tiles[x, y], color);
+                    character.name = reader.GetAttribute("name");
```
Comment (TomMalbran) [inline Assets/Scripts/Models/World.cs]: You could move this and the next line outside of the if/else so that we don't need to repeat code at lines 1082 and 1083.

File: Assets/Scripts/Models/Character.cs (hunk 3 above)
Comment (TomMalbran) [inline Assets/Scripts/Models/Character.cs]: Remove this empty line.

**Comment by vogonistic** [comment]
I can't save and load. I get some errors in the console, these is the one that seems the most relevant:

```
ArgumentNullException: Argument cannot be null.
Parameter name: s
System.Int32.Parse (System.String s) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Int32.cs:629)
World.ReadXml_Inventories (System.Xml.XmlReader reader) (at Assets/Scripts/Models/World.cs:1076)
World.ReadXml (System.Xml.XmlReader reader) (at Assets/Scripts/Models/World.cs:489)
System.Xml.Serialization.XmlSerializationReader.ReadSerializable (IXmlSerializable serializable)
System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadXmlSerializableElement (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable)
System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
```

```
NullReferenceException: Object reference not set to an instance of an object
TileSpriteController.Render () (at Assets/Scripts/Controllers/TileSpriteController.cs:34)
WorldController.Start () (at Assets/Scripts/Controllers/WorldController.cs:102)
```

**Comment by vogonistic** [comment]
I get 2 StyleCop warnings on this branch. Seems like only one is because of this PR at a brief glance.

**Comment by koosemose** [comment]
I get no Stylecop violations on my local branch, but regardless, I'll get this unconflicted, then see if I can recreate the crash, then run a stylecop check.

Was anything special done to cause the crash? Or did it just crash on any old save/load attempt?

**Comment by vogonistic** [comment]
I built a smelter, saved and loaded. I tried it twice to be sure.

**Comment by koosemose** [comment]
Ah hah! It's the smelter specifically that was the issue. I'm guessing it keeps track of its own inventory rather than the inventory just being on the ground in the appropriate spot (at a guess).

Should I fix that bug in this PR as it's indicative of the issue I claim to fix on this one or do it in a separate PR as it's not part of Character inventory saving/loading?

**Comment by koosemose** [comment]
After much testing I've managed to reliably recreate what I suspect is the most likely thing caused by the smeltery, which is multiple characters moving inventories at once, which does cause an error matching the one you reported, I didn't properly step out of the Inventories tag under character, which caused the ReadToNextSibling to fail which in turn caused it to go back to searching for toplevel tags, and eventually end up reading the next character's Inventory as a regular inventory, and trying to read X and Y from it, which of course fail and cascade errors from there due to not being at what depth it thinks it is. 

Anyway that's sorted out, going to Stylecop things and give this another go.

**Comment by koosemose** [comment]
I am confident this will pass all tests, I've tested every combination of characters carrying inventory I can think of, including a few artificially complex scenarios (save editing 10+ characters to have an assortment of "Carrying Inventory" and "Not Carrying Inventory", in several configurations).

**Comment by Mizipzor** [comment]
Nice.

**Comment by vogonistic** [comment]
Excellent job!
