### PR TITLE
LocalizationDownloader fix

### LINKED ISSUE #1428: Stop localization downloader from clobbering en_US defaults
From #1418 by @QuiZr:
> It will break stuff: ClearLocalizationDirectory method - after fresh pr in localization repo (which @quill18 still didn't move to the TeamPorcupine account) en_US.lang will be deleted and replaced by nothing.

### PR DESCRIPTION
**Pull request by QuiZr**
Closes #1428

### CODE REVIEW

File: Assets/Scripts/Localization/LocalizationDownloader.cs [hunk 1]
```diff
@@ -226,9 +226,9 @@ private static void OnDownloadLocalizationComplete(Action onLocalizationDownload
                 // called ProjectPorcupineLocalization-*branch name*. Now we need to move all files from that directory
                 // to Application.streamingAssetsPath/Localization.
                 FileInfo[] fileInfo = localizationFolderInfo.GetFiles();
-                if (fileInfo.Length > 0)
+                if (fileInfo.Length > 2)
```
Comment (mikejbrown) [inline Assets/Scripts/Localization/LocalizationDownloader.cs]: Should explicitly check filenames instead??

Comment (sboigelot) [inline Assets/Scripts/Localization/LocalizationDownloader.cs]: && fileInfo.All(fi => fi.Name.StartWith("en_US.lang")

(this may have issue as I just wrote it in github; but something like that may do the trick)

Comment (mikejbrown) [inline Assets/Scripts/Localization/LocalizationDownloader.cs]: Looks reasonable...

**Comment by QuiZr** [comment]
Ok, it's fixed now. It still makes no sense because en_US will be the most outdated localization..

**Comment by TomMalbran** [comment]
The point is that everyone adding something that requires localization should add the localization in the PR. Which means, that en_US should always be up to date, and every other localization can be based from that one.

File: Assets/Scripts/Localization/LocalizationDownloader.cs (hunk 1 above)
Comment (QuiZr) [inline Assets/Scripts/Localization/LocalizationDownloader.cs]: I really hate lambda expressions - they are really unclear to me and every time I see one I need to spend like 5 minutes figuring out what it does - hence I didn't use it.
