### PR TITLE
Fixing overlapping build jobs

### LINKED ISSUE #181: Jobs can be defined on top of each other
When you have placed a multitile furniture job it is possible to create more jobs overlapping it. And you can place multitile jobs overlapping existing jobs. As shown in the picture:
image
I am working on a fix for this

### PR DESCRIPTION
**Pull request by emilkris33**
Build jobs could previously be placed overlapping as long as they did not have the same lower left corner.

Building preview color also reflects this change

fixes #181

### CODE REVIEW

**Comment by Mizipzor** [comment]
What happened to the file in 0a020ad?

**Comment by BeefEX** [comment]
@Mizipzor it looks like he pasted in LUA code

**Comment by emilkris33** [comment]
@Mizipzor Good question but I think I have it fixed. As you can see that file is not included on this PRs Files changed tab

File: Assets/Scripts/Controllers/BuildModeController.cs [hunk 1]
```diff
@@ -190,5 +193,21 @@ public void DoBuild(Tile t)
 
     }
 
+    public bool BuildJobWouldOverlapExistingBuildJob(Tile t, string furnitureType)
```
Comment (bjubes) [inline Assets/Scripts/Controllers/BuildModeController.cs]: maybe change function name to something like "DoesBuildJobOverlapExistingBuildJob" since it makes it more clear that it returns a bool by making the name a question.

Comment (emilkris33) [inline Assets/Scripts/Controllers/BuildModeController.cs]: @bjubes That is exactly what i was going for, but i could not get the wording right. Thank you.

**Comment by quill18** [comment]
Merged!
